language: node_js
dist: focal
addons:
  chrome: stable
  firefox: latest
branches:
  only:
    - master
before_script:
  - npm run test -- --silent
  - npm run lint
script:
  - npm run build
after_script:
  - npm run test:coverage
  - npm run test:coverage:report
after_success:
  - npm run semantic-release
